# Compatibility filename for docker_open5gs entrypoint variants.
logger:
  file:
    path: /var/log/open5gs/scp.log

scp:
  sbi:
    server:
      - address: 10.10.2.21
        port: 7777
      - address: 10.10.3.32
        port: 7777
    client:
      # Open5GS MEASURED: only ONE nrf client URI.
      nrf:
        - uri: http://10.10.2.10:7777
