# Compatibility filename for docker_open5gs entrypoint variants.
logger:
  file:
    path: /var/log/open5gs/upf.log
upf:
  pfcp:
    server:
      - address: 10.10.2.13
    client:
      smf:
        - address: 10.10.2.12
  gtpu:
    server:
      - address: 10.10.2.13
  subnet:
    - addr: 10.46.0.1/16
      dnn: internet
      dev: ogstun
  metrics:
    server:
      - address: 10.10.2.13
        port: 9090
