# Compatibility filename for docker_open5gs entrypoint variants.
logger:
  file:
    path: /var/log/open5gs/nrf.log

nrf:
  serving:
    - plmn_id:
        mcc: "999"
        mnc: "70"
    - plmn_id:
        mcc: "001"
        mnc: "01"
  sbi:
    server:
      - address: 10.10.2.10
        port: 7777
      - address: 10.10.3.30
        port: 7777
